SELECT COMPONENT.INGREDIENT_ID, COMPONENT.CATEGORY_ID, COMPONENT.FLAVOR_ID, RECIPE_COMPONENT.QUANTITY, RECIPE_COMPONENT.RECIPE_ID 
    FROM COMPONENT COMPONENT JOIN RECIPE_COMPONENT ON COMPONENT.ID = RECIPE_COMPONENT.COMPONENT_ID;

CREATE TABLE NEW_COMPONENT (
    ID NUMBER(20) PRIMARY KEY,
    RECIPE_ID NUMBER(20) NOT NULL,
    CONSTRAINT FK_COMPONENT_RECIPE_NEW FOREIGN KEY (RECIPE_ID) REFERENCES RECIPE(ID),
    INGREDIENT_ID NUMBER(20),
    CONSTRAINT FK_COMPONENT_INGREDIENT_NEW FOREIGN KEY (INGREDIENT_ID) REFERENCES INGREDIENT(ID),
    CATEGORY_ID NUMBER(20),
    CONSTRAINT FK_COMPONENT_CATEGORY_NEW FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID),
    FLAVOR_ID NUMBER(20),
    CONSTRAINT FK_COMPONENT_FLAVOR_NEW FOREIGN KEY (FLAVOR_ID) REFERENCES FLAVOR(ID),
    QUANTITY NUMBER(10) NOT NULL
);
CREATE SEQUENCE NEW_COMPONENT_SEQ;

INSERT INTO NEW_COMPONENT (ID, QUANTITY, RECIPE_ID) SELECT NEW_COMPONENT_SEQ.NEXTVAL, 2, 2 FROM DUAL;
INSERT INTO NEW_COMPONENT (ID, CATEGORY_ID, QUANTITY, RECIPE_ID) SELECT NEW_COMPONENT_SEQ.NEXTVAL, 12, 1, 1 FROM DUAL;
INSERT INTO NEW_COMPONENT (ID, CATEGORY_ID, QUANTITY, RECIPE_ID) SELECT NEW_COMPONENT_SEQ.NEXTVAL, 2, 1, 2 FROM DUAL;
COMMIT;